In [1]:
from flame import *
import numpy as np

# FLA_Cont
## 1x3_to_1x2

In [2]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
AL, AR = FLA_Cont_with_1x3_to_1x2(A0=A[:, 0],
                                  A1=A[:, 1],
                                  A2=A[:, 2],
                                  side="FLA_LEFT")

AL, AR

(array([[1, 2],
        [4, 5],
        [7, 8]]),
 array([[3],
        [6],
        [9]]))

In [4]:
AL, AR = FLA_Cont_with_1x3_to_1x2(A0=A[:, 0],
                                  A1=A[:, 1],
                                  A2=A[:, 2],
                                  side="FLA_RIGHT")

AL, AR

(array([[1],
        [4],
        [7]]),
 array([[2, 3],
        [5, 6],
        [8, 9]]))

## 3x1_to_2x1

In [5]:
AT, AB = FLA_Cont_with_3x1_to_2x1(A0=A[0, :],
                                  A1=A[1, :],
                                  A2=A[2:, :],
                                  side="FLA_TOP")
AT, AB

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[7, 8, 9]]))

In [6]:
AT, AB = FLA_Cont_with_3x1_to_2x1(A0=A[0, :],
                                  A1=A[1, :],
                                  A2=A[2:, :],
                                  side="FLA_BOTTOM")
AT, AB

(array([[1, 2, 3]]),
 array([[4, 5, 6],
        [7, 8, 9]]))

## 3x3_to_2x2

In [7]:
ATL, ATR, ABL, ABR = FLA_Cont_with_3x3_to_2x2(A00=A[0, 0],
                                              A01=A[0, 1],
                                              A02=A[0, 2],
                                              A10=A[1, 0],
                                              A11=A[1, 1],
                                              A12=A[1, 2],
                                              A20=A[2, 0],
                                              A21=A[2, 1],
                                              A22=A[2, 2],
                                              quadrant="FLA_TL")
ATL, ATR, ABL, ABR

(array([[1, 2],
        [4, 5]]),
 array([[3],
        [6]]),
 array([[7, 8]]),
 array([[9]]))

In [8]:
ATL, ATR, ABL, ABR = FLA_Cont_with_3x3_to_2x2(A00=A[0, 0],
                                              A01=A[0, 1],
                                              A02=A[0, 2],
                                              A10=A[1, 0],
                                              A11=A[1, 1],
                                              A12=A[1, 2],
                                              A20=A[2, 0],
                                              A21=A[2, 1],
                                              A22=A[2, 2],
                                              quadrant="FLA_TR")
ATL, ATR, ABL, ABR

(array([[1],
        [4]]),
 array([[2, 3],
        [5, 6]]),
 array([[7]]),
 array([[8, 9]]))

In [9]:
ATL, ATR, ABL, ABR = FLA_Cont_with_3x3_to_2x2(A00=A[0, 0],
                                              A01=A[0, 1],
                                              A02=A[0, 2],
                                              A10=A[1, 0],
                                              A11=A[1, 1],
                                              A12=A[1, 2],
                                              A20=A[2, 0],
                                              A21=A[2, 1],
                                              A22=A[2, 2],
                                              quadrant="FLA_BL")
ATL, ATR, ABL, ABR

(array([[1, 2]]),
 array([[3]]),
 array([[4, 5],
        [7, 8]]),
 array([[6],
        [9]]))

In [10]:
ATL, ATR, ABL, ABR = FLA_Cont_with_3x3_to_2x2(A00=A[0, 0],
                                              A01=A[0, 1],
                                              A02=A[0, 2],
                                              A10=A[1, 0],
                                              A11=A[1, 1],
                                              A12=A[1, 2],
                                              A20=A[2, 0],
                                              A21=A[2, 1],
                                              A22=A[2, 2],
                                              quadrant="FLA_BR")
ATL, ATR, ABL, ABR

(array([[1]]),
 array([[2, 3]]),
 array([[4],
        [7]]),
 array([[5, 6],
        [8, 9]]))

# FLA_Part

In [11]:
A = np.random.normal(size=(5, 5))

A

array([[-0.79799126, -1.16703859, -1.00781106,  0.35731705, -0.67911133],
       [-0.97607414, -1.56275613,  0.69778243, -1.48459135, -2.52966261],
       [-0.30220238, -1.0961619 , -0.13051155, -1.84074622,  1.74953957],
       [-1.72682255, -0.69084257,  1.55535419, -0.50862122,  0.10300934],
       [-0.828981  ,  0.43974438, -0.68082967, -1.16313854,  0.23418778]])

## 1x2

In [12]:
AL, AR = FLA_Part_1x2(A=A, nb=1, side="FLA_LEFT")

AL, AR

(array([[-0.79799126],
        [-0.97607414],
        [-0.30220238],
        [-1.72682255],
        [-0.828981  ]]),
 array([[-1.16703859, -1.00781106,  0.35731705, -0.67911133],
        [-1.56275613,  0.69778243, -1.48459135, -2.52966261],
        [-1.0961619 , -0.13051155, -1.84074622,  1.74953957],
        [-0.69084257,  1.55535419, -0.50862122,  0.10300934],
        [ 0.43974438, -0.68082967, -1.16313854,  0.23418778]]))

In [13]:
AL, AR = FLA_Part_1x2(A=A, nb=1, side="FLA_RIGHT")

AL, AR

(array([[-0.79799126, -1.16703859, -1.00781106,  0.35731705],
        [-0.97607414, -1.56275613,  0.69778243, -1.48459135],
        [-0.30220238, -1.0961619 , -0.13051155, -1.84074622],
        [-1.72682255, -0.69084257,  1.55535419, -0.50862122],
        [-0.828981  ,  0.43974438, -0.68082967, -1.16313854]]),
 array([[-0.67911133],
        [-2.52966261],
        [ 1.74953957],
        [ 0.10300934],
        [ 0.23418778]]))

## 2x1

In [14]:
AT, AB = FLA_Part_2x1(A=A, mb=1, side="FLA_TOP")

AT, AB

(array([[-0.79799126, -1.16703859, -1.00781106,  0.35731705, -0.67911133]]),
 array([[-0.97607414, -1.56275613,  0.69778243, -1.48459135, -2.52966261],
        [-0.30220238, -1.0961619 , -0.13051155, -1.84074622,  1.74953957],
        [-1.72682255, -0.69084257,  1.55535419, -0.50862122,  0.10300934],
        [-0.828981  ,  0.43974438, -0.68082967, -1.16313854,  0.23418778]]))

In [15]:
AT, AB = FLA_Part_2x1(A=A, mb=1, side="FLA_BOTTOM")

AT, AB

(array([[-0.79799126, -1.16703859, -1.00781106,  0.35731705, -0.67911133],
        [-0.97607414, -1.56275613,  0.69778243, -1.48459135, -2.52966261],
        [-0.30220238, -1.0961619 , -0.13051155, -1.84074622,  1.74953957],
        [-1.72682255, -0.69084257,  1.55535419, -0.50862122,  0.10300934]]),
 array([[-0.828981  ,  0.43974438, -0.68082967, -1.16313854,  0.23418778]]))

## 2x2

In [16]:
ATL, ATR, ABL, ABR = FLA_Part_2x2(A=A, mb=2, nb=3, quadrant="FLA_TL")

ATL, ATR, ABL, ABR

(array([[-0.79799126, -1.16703859, -1.00781106],
        [-0.97607414, -1.56275613,  0.69778243]]),
 array([[ 0.35731705, -0.67911133],
        [-1.48459135, -2.52966261]]),
 array([[-0.30220238, -1.0961619 , -0.13051155],
        [-1.72682255, -0.69084257,  1.55535419],
        [-0.828981  ,  0.43974438, -0.68082967]]),
 array([[-1.84074622,  1.74953957],
        [-0.50862122,  0.10300934],
        [-1.16313854,  0.23418778]]))

In [17]:
ATL, ATR, ABL, ABR = FLA_Part_2x2(A=A, mb=2, nb=3, quadrant="FLA_TR")

ATL, ATR, ABL, ABR

(array([[-0.79799126, -1.16703859],
        [-0.97607414, -1.56275613]]),
 array([[-1.00781106,  0.35731705, -0.67911133],
        [ 0.69778243, -1.48459135, -2.52966261]]),
 array([[-0.30220238, -1.0961619 ],
        [-1.72682255, -0.69084257],
        [-0.828981  ,  0.43974438]]),
 array([[-0.13051155, -1.84074622,  1.74953957],
        [ 1.55535419, -0.50862122,  0.10300934],
        [-0.68082967, -1.16313854,  0.23418778]]))

In [18]:
ATL, ATR, ABL, ABR = FLA_Part_2x2(A=A, mb=2, nb=3, quadrant="FLA_BL")

ATL, ATR, ABL, ABR

(array([[-0.79799126, -1.16703859, -1.00781106],
        [-0.97607414, -1.56275613,  0.69778243],
        [-0.30220238, -1.0961619 , -0.13051155]]),
 array([[ 0.35731705, -0.67911133],
        [-1.48459135, -2.52966261],
        [-1.84074622,  1.74953957]]),
 array([[-1.72682255, -0.69084257,  1.55535419],
        [-0.828981  ,  0.43974438, -0.68082967]]),
 array([[-0.50862122,  0.10300934],
        [-1.16313854,  0.23418778]]))

In [19]:
ATL, ATR, ABL, ABR = FLA_Part_2x2(A=A, mb=2, nb=3, quadrant="FLA_BR")

ATL, ATR, ABL, ABR

(array([[-0.79799126, -1.16703859],
        [-0.97607414, -1.56275613],
        [-0.30220238, -1.0961619 ]]),
 array([[-1.00781106,  0.35731705, -0.67911133],
        [ 0.69778243, -1.48459135, -2.52966261],
        [-0.13051155, -1.84074622,  1.74953957]]),
 array([[-1.72682255, -0.69084257],
        [-0.828981  ,  0.43974438]]),
 array([[ 1.55535419, -0.50862122,  0.10300934],
        [-0.68082967, -1.16313854,  0.23418778]]))

# FLA_Repart

In [20]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 1x2_to_1x3

In [21]:
AL, AR = FLA_Cont_with_1x3_to_1x2(A0=A[:, 0],
                                  A1=A[:, 1],
                                  A2=A[:, 2],
                                  side="FLA_LEFT")

AL, AR

(array([[1, 2],
        [4, 5],
        [7, 8]]),
 array([[3],
        [6],
        [9]]))

In [22]:
A0, A1, A2 = FLA_Repart_1x2_to_1x3(AL=AL, AR=AR, nb=1, side="FLA_LEFT")

A0, A1, A2

(array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]]))

In [23]:
AL, AR = FLA_Cont_with_1x3_to_1x2(A0=A[:, 0],
                                  A1=A[:, 1],
                                  A2=A[:, 2],
                                  side="FLA_RIGHT")

AL, AR

(array([[1],
        [4],
        [7]]),
 array([[2, 3],
        [5, 6],
        [8, 9]]))

In [24]:
A0, A1, A2 = FLA_Repart_1x2_to_1x3(AL=AL, AR=AR, nb=1, side="FLA_RIGHT")

A0, A1, A2

(array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]]))

## 2x1_to_3x1

In [25]:
AT, AB = FLA_Cont_with_3x1_to_2x1(A0=A[0, :],
                                  A1=A[1, :],
                                  A2=A[2:, :],
                                  side="FLA_TOP")
AT, AB

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[7, 8, 9]]))

In [26]:
A0, A1, A2 = FLA_Repart_2x1_to_3x1(AT=AT, AB=AB, mb=1, side="FLA_TOP")

A0, A1, A2

(array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]]))

In [27]:
AT, AB = FLA_Cont_with_3x1_to_2x1(A0=A[0, :],
                                  A1=A[1, :],
                                  A2=A[2:, :],
                                  side="FLA_BOTTOM")
AT, AB

(array([[1, 2, 3]]),
 array([[4, 5, 6],
        [7, 8, 9]]))

In [28]:
A0, A1, A2 = FLA_Repart_2x1_to_3x1(AT=AT, AB=AB, mb=1, side="FLA_BOTTOM")

A0, A1, A2

(array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]]))

## 2x2_to_3x3

In [29]:
ATL, ATR, ABL, ABR = FLA_Cont_with_3x3_to_2x2(A00=A[0, 0],
                                              A01=A[0, 1],
                                              A02=A[0, 2],
                                              A10=A[1, 0],
                                              A11=A[1, 1],
                                              A12=A[1, 2],
                                              A20=A[2, 0],
                                              A21=A[2, 1],
                                              A22=A[2, 2],
                                              quadrant="FLA_TL")
ATL, ATR, ABL, ABR

(array([[1, 2],
        [4, 5]]),
 array([[3],
        [6]]),
 array([[7, 8]]),
 array([[9]]))

In [30]:
A00, A01, A02, A10, A11, A12, A20, A21, A22 = FLA_Repart_2x2_to_3x3(
    ATL=ATL, ATR=ATR, ABL=ABL, ABR=ABR, bm=1, bn=1, quadrant="FLA_TL")

A00, A01, A02, A10, A11, A12, A20, A21, A22

(array([[1]]),
 array([[2]]),
 array([[3]]),
 array([[4]]),
 array([[5]]),
 array([[6]]),
 array([[7]]),
 array([[8]]),
 array([[9]]))

In [31]:
ATL, ATR, ABL, ABR = FLA_Cont_with_3x3_to_2x2(A00=A[0, 0],
                                              A01=A[0, 1],
                                              A02=A[0, 2],
                                              A10=A[1, 0],
                                              A11=A[1, 1],
                                              A12=A[1, 2],
                                              A20=A[2, 0],
                                              A21=A[2, 1],
                                              A22=A[2, 2],
                                              quadrant="FLA_TR")
ATL, ATR, ABL, ABR

(array([[1],
        [4]]),
 array([[2, 3],
        [5, 6]]),
 array([[7]]),
 array([[8, 9]]))

In [32]:
A00, A01, A02, A10, A11, A12, A20, A21, A22 = FLA_Repart_2x2_to_3x3(
    ATL=ATL, ATR=ATR, ABL=ABL, ABR=ABR, bm=1, bn=1, quadrant="FLA_TR")

A00, A01, A02, A10, A11, A12, A20, A21, A22

(array([[1]]),
 array([[2]]),
 array([[3]]),
 array([[4]]),
 array([[5]]),
 array([[6]]),
 array([[7]]),
 array([[8]]),
 array([[9]]))

In [33]:
ATL, ATR, ABL, ABR = FLA_Cont_with_3x3_to_2x2(A00=A[0, 0],
                                              A01=A[0, 1],
                                              A02=A[0, 2],
                                              A10=A[1, 0],
                                              A11=A[1, 1],
                                              A12=A[1, 2],
                                              A20=A[2, 0],
                                              A21=A[2, 1],
                                              A22=A[2, 2],
                                              quadrant="FLA_BL")
ATL, ATR, ABL, ABR

(array([[1, 2]]),
 array([[3]]),
 array([[4, 5],
        [7, 8]]),
 array([[6],
        [9]]))

In [34]:
A00, A01, A02, A10, A11, A12, A20, A21, A22 = FLA_Repart_2x2_to_3x3(
    ATL=ATL, ATR=ATR, ABL=ABL, ABR=ABR, bm=1, bn=1, quadrant="FLA_BL")

A00, A01, A02, A10, A11, A12, A20, A21, A22

(array([[1]]),
 array([[2]]),
 array([[3]]),
 array([[4]]),
 array([[5]]),
 array([[6]]),
 array([[7]]),
 array([[8]]),
 array([[9]]))

In [35]:
ATL, ATR, ABL, ABR = FLA_Cont_with_3x3_to_2x2(A00=A[0, 0],
                                              A01=A[0, 1],
                                              A02=A[0, 2],
                                              A10=A[1, 0],
                                              A11=A[1, 1],
                                              A12=A[1, 2],
                                              A20=A[2, 0],
                                              A21=A[2, 1],
                                              A22=A[2, 2],
                                              quadrant="FLA_BR")
ATL, ATR, ABL, ABR

(array([[1]]),
 array([[2, 3]]),
 array([[4],
        [7]]),
 array([[5, 6],
        [8, 9]]))

In [36]:
A00, A01, A02, A10, A11, A12, A20, A21, A22 = FLA_Repart_2x2_to_3x3(
    ATL=ATL, ATR=ATR, ABL=ABL, ABR=ABR, bm=1, bn=1, quadrant="FLA_BR")

A00, A01, A02, A10, A11, A12, A20, A21, A22

(array([[1]]),
 array([[2]]),
 array([[3]]),
 array([[4]]),
 array([[5]]),
 array([[6]]),
 array([[7]]),
 array([[8]]),
 array([[9]]))