In [1]:
from functions import *
import random

In [2]:
# seed the random number generator so that we all
random.seed(0)

# Create random m x n matrix A
m = 5
n = 4
A = np.random.normal(size=(m, n))

# Call HQR
A_out, t_out = HQR(A)

# Set R = upper triangular part of A
R = np.triu(A_out[:n, :])

# FormQ
Q = FormQ(A_out, t_out)

In [3]:
# Check A - Q * R
print("A - Q * R =\n{}".format(A - np.dot(Q, R)))

A - Q * R =
[[-2.22044605e-16 -2.22044605e-16 -3.33066907e-16 -1.11022302e-16]
 [ 0.00000000e+00 -5.55111512e-17  4.44089210e-16  2.22044605e-16]
 [ 0.00000000e+00  5.55111512e-17  0.00000000e+00  2.22044605e-16]
 [ 0.00000000e+00  4.44089210e-16 -1.11022302e-16 -2.22044605e-16]
 [-1.11022302e-16 -1.38777878e-16 -1.11022302e-16  5.55111512e-17]]


In [5]:
# Report norm( A - Q * R )
print("norm( A - Q * R ) = {}".format(np.linalg.norm(A - np.dot(Q, R))))

norm( A - Q * R ) = 9.10873547778187e-16
