In [1]:
from functions import *
import random

In [2]:
# seed the random number generator so that we all
random.seed(0)

# Create random m x n matrix A
m = 5
n = 4
A = np.random.normal(size=(m, n))

# Call HQR
A_out, t_out = HQR(A)

In [3]:
print("> R computed by HQR")
print("R =\n{}".format(np.triu(A_out[:n, :])))

> R computed by HQR
R =
[[ 1.0933807   0.70088524 -1.08421005  1.79212576]
 [ 0.          1.41026166  0.94677598 -1.05196427]
 [ 0.          0.          1.04684648 -0.31983404]
 [ 0.          0.          0.         -1.05666621]]


In [4]:
# Call numpy's qr routine
Q, R = np.linalg.qr(A)

In [5]:
print("> R computed by qr (numpy routine)")
print("R =\n{}".format(R))

> R computed by qr (numpy routine)
R =
[[ 1.0933807   0.70088524 -1.08421005  1.79212576]
 [ 0.          1.41026166  0.94677598 -1.05196427]
 [ 0.          0.          1.04684648 -0.31983404]
 [ 0.          0.          0.         -1.05666621]]


In [6]:
print("> Report difference")
print(np.triu(A_out[:n, :]) - R)

> Report difference
[[-2.22044605e-16  0.00000000e+00 -4.44089210e-16 -4.44089210e-16]
 [ 0.00000000e+00 -2.22044605e-16  1.11022302e-16  4.44089210e-16]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -2.22044605e-16]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  2.22044605e-16]]


In [7]:
print("> Warning: since diagonal elements of R are not chosen to be positive")
print("           R may not be unique")

> Warning: since diagonal elements of R are not chosen to be positive
           R may not be unique
