In [1]:
from functions import *
import random

In [2]:
# seed the random number generator so that we all
random.seed(0)

# Create random m x n matrix A
m = 4
n = 5
A = np.random.normal(size=(m, n))

# Call HLQ
A_out, t_out = HLQ(A)

In [3]:
print("> A_out computed by HLQ")
print("A_out =\n{}".format(A_out))

> A_out computed by HLQ
A_out =
[[-2.43482343 -0.52377276  0.36627437 -0.23410367 -0.34013752]
 [-1.06364102 -1.22976523  0.3718877   0.64838062 -0.10049755]
 [-0.19415521  2.07242318 -1.26541416 -0.15452941  0.42849783]
 [-0.8758329   0.71329319 -2.30687383  0.79300935 -0.31309219]]


In [4]:
# Call the HQR routine we wrote, with the transpose matrix
A_out_QR, t_out_QR = HQR(np.transpose(A))

In [5]:
print("> A_out_QR computed by HQR")
print("A_out_QR =\n{}".format(A_out_QR))

> A_out_QR computed by HQR
A_out_QR =
[[-2.43482343 -1.06364102 -0.19415521 -0.8758329 ]
 [-0.52377276 -1.22976523  2.07242318  0.71329319]
 [ 0.36627437  0.3718877  -1.26541416 -2.30687383]
 [-0.23410367  0.64838062 -0.15452941  0.79300935]
 [-0.34013752 -0.10049755  0.42849783 -0.31309219]]


In [6]:
print("> Report difference (should be the zero matrix)")
print("A_out - A_out_QR' =\n{}".format(A_out - np.transpose(A_out_QR)))

> Report difference (should be the zero matrix)
A_out - A_out_QR' =
[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [ 5.55111512e-17  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [ 2.22044605e-16  1.11022302e-16  0.00000000e+00 -2.22044605e-16
  -5.55111512e-17]]
